export type InitiativeType = 'national' | 'state' | ''
export type ElectionStatus =
    | ''
    | 'Won Primary'
    | 'Elected'
    | 'Lost Primary'
    | 'Lost General Election'
    | 'Dropped Out'

export interface CandidateConfig {
    id: string
    name: string
    state: string
    electionStatus: ElectionStatus
    electionDate?: Date

    handle: string
    handleHref?: string
    bodyText: string

    image: string
    learnMoreHref: string

    initiativeType: InitiativeType
    showPvPledge: boolean
    showPvMember: boolean
}

export const CANDIDATES: CandidateConfig[] = [
    {
        id: '1',
        name: 'Jeromie Whalen',
        state: 'Massachusetts',
        electionStatus: '',
        electionDate: new Date('09/01/26'),
        handle: '@jeromiewhalen',
        handleHref: 'https://www.whalenforcongressma.com/',
        bodyText:
            ' is not only a passionate progressive voice, he is also a powerful member of our community! There is nobody we are more excited to endorse this midterm season!',
        image: '/images/endorsement_images/2026/JEROMIE WHALEN.png',
        learnMoreHref: 'https://www.whalenforcongressma.com/platform',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '2',
        name: 'Abdul El-Sayed',
        state: 'Michigan',
        electionStatus: '',
        electionDate: new Date('11/03/26'),
        handle: '@abdulelsayed',
        handleHref: 'https://x.com/AbdulElSayed',
        bodyText:
            ' is challenging the status quo by embracing new ways to reach voters! With RFK and Trump’s attacks on medicine, a doctor like him is exactly what we need to pass Medicare For All!',
        image: '/images/endorsement_images/2026/ABDUL EL-SAYED.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '3',
        name: 'Saikat Chakrabarti',
        state: 'California',
        electionStatus: '',
        electionDate: new Date('06/02/26'),
        handle: '@saikatc',
        handleHref: 'https://x.com/saikatc',
        bodyText:
            " founded the Justice Democrats because he belives in the left's ability to come togeather to fight establishment power. In congress, he will continue that energy!",
        image: '/images/endorsement_images/2026/SAIKAT CHAKRABARTI.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '4',
        name: 'Kat Abughazaleh',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        electionDate: new Date('03/17/26'),
        handle: '@katabughazaleh',
        handleHref: 'https://x.com/KatAbughazaleh',
        bodyText:
            ' is exactly what we are looking for at PV. A young, media savvy firebrand willing to tackle any challenge that gets in her way.',
        image: '/images/endorsement_images/2026/KAT ABUGHAZALEH.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '5',
        name: 'Graham Platner',
        state: 'Maine',
        electionStatus: 'Won Primary',
        electionDate: new Date('11/03/26'),
        handle: '@grahamformaine',
        handleHref: 'https://x.com/grahamformaine',
        bodyText:
            ' is what happens when normal people get fed up and run for office over sanitized aspiring political wannabes! Our Maine team is so excited to get to work on his behalf!',
        image: '/images/endorsement_images/2026/GRAHAM PLATNER.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '6',
        name: 'Salaam Bhatti',
        state: 'Virginia',
        electionStatus: '',
        electionDate: new Date('08/01/26'),
        handle: '@salaambhattiva',
        handleHref: 'https://x.com/SalaamBhattiVA',
        bodyText:
            ' is a candidate whose advocacy for Medicare for All and drive to fight to get money out of politics will bring us one step closer to free healthcare once he wins his district.',
        image: '/images/endorsement_images/2026/SALAAM BHATTI.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '7',
        name: 'Karishma Manzur',
        state: 'North Carolina',
        electionStatus: '',
        electionDate: new Date('09/08/26'),
        handle: '@karishma4senate',
        handleHref: 'https://x.com/Karishma4Senate',
        bodyText: '',
        image: '/images/endorsement_images/2026/KARISHMA MANZUR.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '8',
        name: 'Oliver Larkin',
        state: 'Florida',
        electionStatus: '',
        electionDate: new Date('08/18/26'),
        handle: '@oliveralarkin',
        handleHref: 'https://x.com/OliverALarkin',
        bodyText:
            ' is proving Progressive politics is alive and well even in places like Florida! We are proud to endorse him and to do our part to help him win.',
        image: '/images/endorsement_images/2026/OLIVER LARKIN.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '9',
        name: 'Heath Howard',
        state: 'New Hampshire',
        electionStatus: '',
        electionDate: new Date('09/08/26'),
        handle: '@heathhowardnh',
        handleHref: 'https://x.com/HeathHowardNH',
        bodyText: '',
        image: '/images/endorsement_images/2026/HEATH HOWARD.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '10',
        name: 'Adam Murphy',
        state: 'Virginia',
        electionStatus: '',
        electionDate: new Date('08/01/26'),
        handle: '@murphy4va',
        handleHref: 'https://x.com/Murphy4VA',
        bodyText:
            ' has quickly become a beloved presence in the PV community. We are proud to endorse him for Virginia’s 9th Congressional District.',
        image: '/images/endorsement_images/2026/ADAM MURPHY.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '11',
        name: 'Analilia Mejia',
        state: 'New Jersey',
        electionStatus: 'Elected',
        electionDate: new Date('02/05/26'),
        handle: '@analilia_mejia',
        handleHref: 'https://x.com/Analilia_Mejia',
        bodyText:
            ' is a life long organizer who will be instrumental in organizing the progressive movement from within congress! We are thrilled to endorse her, and to see her take the PV Pledge.',
        image: '/images/endorsement_images/2026/ANALILIA_MEJIA.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '12',
        name: 'Mary Peltola',
        state: 'Alaska',
        electionStatus: '',
        electionDate: new Date('11/03/26'),
        handle: '@marypeltola',
        handleHref: 'https://x.com/MaryPeltola',
        bodyText:
            " is America's first Native Alaskan representative and a fierce advocate for her community. We are proud to endorse her for re-election in Alaska's at-large congressional district!",
        image: '/images/endorsement_images/2026/MARY PELTOLA.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '13',
        name: 'Erica Watkins',
        state: 'Oklahoma',
        electionStatus: 'Dropped Out',
        electionDate: new Date('11/03/26'),
        handle: '@erica4ok',
        handleHref: 'https://x.com/erica4ok',
        bodyText:
            " stands apart not just as someone who will take on the machine, but someone with bold ideas to fight Oklahoma's poverty and exploitation.",
        image: '/images/endorsement_images/2026/ERICA WATKINS.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '14',
        name: 'Taylor Rehmet',
        state: 'Texas',
        electionStatus: 'Elected',
        electionDate: new Date('01/27/26'),
        handle: '@taylorrehmettx',
        handleHref: 'https://x.com/TaylorRehmetTX',
        bodyText: '',
        image: '/images/endorsement_images/2026/TAYLOR REHMET.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '15',
        name: 'Luis Villarreal',
        state: 'Utah',
        electionStatus: '',
        electionDate: new Date('11/03/26'),
        handle: '@luis4utah',
        handleHref: 'https://x.com/Luis4Utah',
        bodyText: '',
        image: '/images/endorsement_images/2026/LUIS VILLARREAL.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '16',
        name: 'Brad Lander',
        state: 'New York',
        electionStatus: '',
        electionDate: new Date('11/03/26'),
        handle: '@bradlander',
        handleHref: 'https://x.com/bradlander',
        bodyText: '',
        image: '/images/endorsement_images/2026/BRAD LANDER.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '17',
        name: 'Ro Khanna',
        state: 'California',
        electionStatus: '',
        electionDate: new Date('11/03/26'),
        handle: '@rokhanna',
        handleHref: 'https://x.com/RoKhanna',
        bodyText:
            ' is the leader our party needs! His commitment to new media politics has made him an outstanding voice capable of real change.',
        image: '/images/endorsement_images/2026/RO KHANNA.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '18',
        name: 'Cori Bush',
        state: 'Missouri',
        electionStatus: '',
        electionDate: new Date('08/04/26'),
        handle: '@coribush',
        handleHref: 'https://x.com/CoriBush',
        bodyText:
            ' is back to finish what she started! Her passion and tenacity have repeatedly shown that she is a powerful progressive voice ready to take on whatever battle is needed.',
        image: '/images/endorsement_images/2026/CORI BUSH.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '19',
        name: 'James Talarico',
        state: 'Texas',
        electionStatus: 'Won Primary',
        electionDate: new Date('03/03/26'),
        handle: '@jamestalarico',
        handleHref: 'https://x.com/jamestalarico',
        bodyText:
            "'s time has come to turn Texas blue. PV is proud to endorse him for the US Senate Seat in Texas! He is exctly what is needed.",
        image: '/images/endorsement_images/2026/JAMES TALARICO.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: false,
        showPvMember: false,
    },
    // {
    //     id: '20',
    //     name: 'Jon Stewart',
    //     state: 'President',
    //     electionStatus: '',
    //     electionDate: new Date('11/07/28'),
    //     handle: '@jonstewart',
    //     handleHref: 'https://x.com/jonstewart',
    //     bodyText:
    //         ' isn’t perfect, but his decades long track record of integrity and progressivism make him the decisive pick. We urge him to serve his country by running for the office.',
    //     image: '/images/endorsement_images/2028/JON STEWART.png',
    //     learnMoreHref: '',
    //     initiativeType: '',
    //     showPvPledge: false,
    //     showPvMember: false,
    // },
    {
        id: '21',
        name: 'Zeeshan Hafeez',
        state: 'Texas',
        electionStatus: 'Lost Primary',
        electionDate: new Date('03/03/26'),
        handle: '@zeeshanfortexas',
        handleHref: '',
        bodyText:
            " is going to bring a fire to Texa's 33rd Congressional District. We are excited to see a bold progressive like him making all the right waves in all the right places!",
        image: '/images/endorsement_images/2026/ZEESHAN HAFEEZ.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '22',
        name: 'Michael Black',
        state: 'New York',
        electionStatus: '',
        electionDate: new Date('06/23/26'),
        handle: '@MrMikeBlake',
        handleHref: 'https://x.com/MrMikeBlake',
        bodyText:
            ' is an authentic, progressive fighter who has a deep love for his community. The progressive movement won in New Jersey and he will bring that momentum to New York!',
        image: '/images/endorsement_images/2026/MICHAEL BLAKE.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '23',
        name: 'Aaron Bailey',
        state: 'Maryland',
        electionStatus: '',
        electionDate: new Date('05/19/26'),
        handle: 'baileepolitics',
        handleHref: 'https://x.com/BaileePolitics',
        bodyText: '',
        image: '/images/endorsement_images/2026/AARON BAILEY.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '24',
        name: 'Adam Bojak',
        state: 'New Jersey',
        electionStatus: '',
        electionDate: new Date('06/23/26'),
        handle: 'bojak4assembly',
        handleHref: 'https://x.com/bojak4assembly',
        bodyText: '',
        image: '/images/endorsement_images/2026/ADAM BOJAK.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '25',
        name: 'Beth Andres-Beck',
        state: 'Massachusetts',
        electionStatus: '',
        electionDate: new Date('09/01/26'),
        handle: 'beth4ma',
        handleHref: 'https://x.com/beth4ma',
        bodyText: '',
        image: '/images/endorsement_images/2026/BETH ANDRES-BECK.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '26',
        name: 'Blake Bracht',
        state: 'Arizona',
        electionStatus: '',
        electionDate: new Date('07/29/26'),
        handle: 'brachtforaz5',
        handleHref: 'https://x.com/BrachtforAZ5',
        bodyText: '',
        image: '/images/endorsement_images/2026/BLAKE BRACHT.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '27',
        name: 'Bobby Nichols',
        state: 'Arizona',
        electionStatus: '',
        electionDate: new Date('07/29/26'),
        handle: 'bobby4tempe',
        handleHref: 'https://www.instagram.com/bobby4tempe/',
        bodyText: '',
        image: '/images/endorsement_images/2026/BOBBY NICHOLS.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '28',
        name: 'Brent Hennrich',
        state: 'Massachusetts',
        electionStatus: '',
        electionDate: new Date('09/01/26'),
        handle: 'bhennrich',
        handleHref: 'https://x.com/bhennrich',
        bodyText: '',
        image: '/images/endorsement_images/2026/BRENT HENNRICH.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '29',
        name: 'Ethan Wechtaluk',
        state: 'Maryland',
        electionStatus: '',
        electionDate: new Date('05/19/26'),
        handle: 'ethanformd',
        handleHref: 'https://x.com/ethanformd',
        bodyText: '',
        image: '/images/endorsement_images/2026/ETHAN WECHTALUK.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '30',
        name: 'Greg Casar',
        state: 'Texas',
        electionStatus: 'Won Primary',
        electionDate: new Date('03/03/26'),
        handle: 'gregcasar',
        handleHref: 'https://x.com/gregcasar',
        bodyText: '',
        image: '/images/endorsement_images/2026/GREG CASAR.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '32',
        name: 'Hunter Gordon',
        state: 'Washington',
        electionStatus: '',
        electionDate: new Date('08/04/26'),
        handle: 'hunter4wa',
        handleHref: 'https://x.com/hunter4wa',
        bodyText: '',
        image: '/images/endorsement_images/2026/HUNTER GORDON.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '33',
        name: 'Jakeya Johnson',
        state: 'Washington',
        electionStatus: '',
        electionDate: new Date('08/04/26'),
        handle: 'jakeya_hq',
        handleHref: 'https://www.instagram.com/jakeya_hq',
        bodyText: '',
        image: '/images/endorsement_images/2026/JAKEYA JOHNSON.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '34',
        name: 'John Padora',
        state: 'Colorado',
        electionStatus: 'Dropped Out',
        electionDate: new Date('06/30/26'),
        handle: 'padoraforco',
        handleHref: 'https://x.com/PadoraforCO',
        bodyText: '',
        image: '/images/endorsement_images/2026/JOHN PADORA.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '35',
        name: 'Josie Caballero',
        state: 'Maryland',
        electionStatus: '',
        electionDate: new Date('05/19/26'),
        handle: 'josieformd',
        handleHref: 'https://x.com/josieformd',
        bodyText: '',
        image: '/images/endorsement_images/2026/JOSIE CABALLERO.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: false,
        showPvMember: true,
    },
    {
        id: '36',
        name: 'Katie Bansil',
        state: 'New Jersey',
        electionStatus: '',
        electionDate: new Date('06/02/26'),
        handle: 'katiebansil4nj',
        handleHref: 'https://x.com/katiebansil4nj',
        bodyText: '',
        image: '/images/endorsement_images/2026/Katie Bansil.png',
        learnMoreHref: '',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: true,
    },
    {
        id: '37',
        name: 'Matt Conroy',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        electionDate: new Date('03/17/26'),
        handle: 'conroyforil',
        handleHref: 'https://x.com/ConroyForIL',
        bodyText: '',
        image: '/images/endorsement_images/2026/MATT CONROY.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '38',
        name: 'Matt Fulmer',
        state: 'North Carolina',
        electionStatus: '',
        electionDate: new Date('05/19/26'),
        handle: 'mattforcarolina',
        handleHref: 'https://x.com/MattForCarolina',
        bodyText: '',
        image: '/images/endorsement_images/2026/MATT FULMER.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '39',
        name: 'Maurice Brown',
        state: 'Florida',
        electionStatus: '',
        electionDate: new Date('03/17/26'),
        handle: 'electmauricebrown',
        handleHref: 'https://www.instagram.com/electmauricebrown',
        bodyText: '',
        image: '/images/endorsement_images/2026/MAURICE BROWN.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '40',
        name: 'Max Diaz',
        state: 'Missouri',
        electionStatus: '',
        electionDate: new Date('08/04/26'),
        handle: 'votemaxdiaz',
        handleHref: 'https://x.com/VoteMaxDiaz',
        bodyText: '',
        image: '/images/endorsement_images/2026/MAX DIAZ.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '41',
        name: 'Maxwell Alejandro Frost',
        state: 'Florida',
        electionStatus: '',
        electionDate: new Date('08/18/26'),
        handle: 'maxwellfrostfl',
        handleHref: 'https://x.com/MaxwellFrostFL',
        bodyText: '',
        image: '/images/endorsement_images/2026/MAXWELL FROST.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '42',
        name: 'Melissa Bird',
        state: 'Alabama',
        electionStatus: '',
        electionDate: new Date('05/19/26'),
        handle: 'melissabirdforcongress',
        handleHref: 'https://www.instagram.com/melissabirdforcongress/',
        bodyText: '',
        image: '/images/endorsement_images/2026/MELISSA BIRD.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '44',
        name: 'Nida Allam',
        state: 'North Carolina',
        electionStatus: 'Lost Primary',
        electionDate: new Date('05/19/26'),
        handle: '',
        handleHref: 'https://x.com/NidaAllam',
        bodyText: '',
        image: '/images/endorsement_images/2026/NIDA_ALLAM.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '45',
        name: 'Robert Arnold',
        state: 'South Dakota',
        electionStatus: 'Dropped Out',
        electionDate: new Date('06/02/26'),
        handle: 'robertarnoldsd',
        handleHref: 'https://x.com/RobertArnoldSD',
        bodyText: '',
        image: '/images/endorsement_images/2026/ROBERT ARNOLD.png',
        learnMoreHref: '',
        initiativeType: 'state',
        showPvPledge: false,
        showPvMember: true,
    },
    {
        id: '46',
        name: 'Val Thomason',
        state: 'Nevada',
        electionStatus: '',
        electionDate: new Date('06/09/26'),
        handle: 'valfornevada',
        handleHref: 'https://x.com/valfornevada',
        bodyText: '',
        image: '/images/endorsement_images/2026/VAL THOMASON.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '47',
        name: 'William Compton',
        state: 'Kentucky',
        electionStatus: 'Lost Primary',
        electionDate: new Date('05/19/26'),
        handle: 'compton4ky2024',
        handleHref: 'https://x.com/Compton4KY2024',
        bodyText: '',
        image: '/images/endorsement_images/2026/WILLIAM COMPTON.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: true,
        showPvMember: false,
    },
    {
        id: '48',
        name: 'Hartzell Gray',
        state: 'Missouri',
        electionStatus: '',
        electionDate: new Date('08/04/26'),
        handle: 'hartzellforkc',
        handleHref: 'https://x.com/hartzellforkc',
        bodyText:
            ' is a bold progressive proving that even in the deepest depths of Republican controlled Missouri, a platform of economic and social justice can make its mark.',
        image: '/images/endorsement_images/2026/HARTZELL GRAY.png',
        learnMoreHref: '',
        initiativeType: '',
        showPvPledge: false,
        showPvMember: false,
    },
    {
        id: '49',
        name: 'Jackson Franklin',
        state: 'Indiana',
        electionStatus: 'Lost Primary',
        electionDate: new Date('05/05/26'),
        handle: 'jacksonfrankli',
        handleHref: 'https://x.com/jacksonfrankli',
        bodyText:
            " has a passionate voice committed to fighting for a better world not just in the U.S. but around the world. We are proud to endorse him for Indiana's 5th Congressional District!",
        image: '/images/endorsement_images/2026/Jackson Franklin.png',
        learnMoreHref: 'https://jacksonfranklinforcongress.com/',
        initiativeType: 'national',
        showPvPledge: true,
        showPvMember: false,
    },
]
