export type InitiativeType = 'national' | 'state' | ''
export type EndorsementType =
    | 'PV Pledge'
    | 'Endorsement'
    | 'Recommendation'
    | 'Unendorsed'
export type AvatarBackgroundColor = 'blue' | 'yellow'
export type ElectionStatus =
    | ''
    | 'Won Primary'
    | 'Elected'
    | 'Lost Primary'
    | 'Lost General'
    | 'Dropped Out'

export interface CandidateConfig {
    id: string
    name: string
    state: string
    electionStatus: ElectionStatus
    jurisdiction?: string
    primaryElection?: Date
    generalElection?: Date
    endorsementDate?: Date
    endorsementReason?: string
    incumbent?: boolean

    handle: string
    handleHref?: string
    bodyText: string

    image: string
    websiteHref: string
    donateHref?: string

    initiativeType: InitiativeType
    endorsementType: EndorsementType
    showPvMember: boolean
    avatarBackgroundColor: AvatarBackgroundColor
    relatedCandidateId?: string
}

export const CANDIDATES: CandidateConfig[] = [
    {
        id: '1',
        name: 'Jeromie Whalen',
        state: 'Massachusetts',
        electionStatus: '',
        primaryElection: new Date('09/01/26'),
        generalElection: new Date('11/03/26'),
        handle: 'jeromiewhalen',
        handleHref: 'https://www.whalenforcongressma.com/',
        bodyText:
            ' is not only a passionate progressive voice, he is also a powerful member of our community! There is nobody we are more excited to endorse this midterm season!',
        image: '/images/endorsement_images/2026/Silhouette/Jeromie Whalen.png',
        websiteHref: 'https://www.whalenforcongressma.com/platform',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '2',
        name: 'Abdul El-Sayed',
        state: 'Michigan',
        electionStatus: 'Won Primary',
        jurisdiction: 'U.S. Senate',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'abdulelsayed',
        handleHref: 'https://x.com/AbdulElSayed',
        bodyText:
            ' is challenging the status quo by embracing new ways to reach voters! With RFK and Trump’s attacks on medicine, a doctor like him is exactly what we need to pass Medicare For All!',
        image: '/images/endorsement_images/2026/Silhouette/Abdul El-Sayed.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '3',
        name: 'Saikat Chakrabarti',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: 'saikatc',
        handleHref: 'https://x.com/saikatc',
        bodyText:
            " founded the Justice Democrats because he belives in the left's ability to come togeather to fight establishment power. In congress, he will continue that energy!",
        image: '/images/endorsement_images/2026/Silhouette/Saikat Chakrabarti.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '4',
        name: 'Kat Abughazaleh',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/17/26'),
        generalElection: new Date('11/03/26'),
        handle: 'katabughazaleh',
        handleHref: 'https://x.com/KatAbughazaleh',
        bodyText:
            ' is exactly what we are looking for at PV. A young, media savvy firebrand willing to tackle any challenge that gets in her way.',
        image: '/images/endorsement_images/2026/Silhouette/Kat Abughazaleh.png',
        websiteHref:
            '/images/endorsement_images/2026/Silhouette/Kat Abughazaleh.png',
        initiativeType: 'national',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '6',
        name: 'Salaam Bhatti',
        state: 'Virginia',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'salaambhattiva',
        handleHref: 'https://x.com/SalaamBhattiVA',
        bodyText:
            ' is a candidate whose advocacy for Medicare for All and drive to fight to get money out of politics will bring us one step closer to free healthcare once he wins his district.',
        image: '/images/endorsement_images/2026/Silhouette/Salaam Bhatti.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '7',
        name: 'Karishma Manzur',
        state: 'New Hampshire',
        electionStatus: '',
        primaryElection: new Date('09/08/26'),
        generalElection: new Date('11/03/26'),
        handle: 'karishma4senate',
        handleHref: 'https://x.com/Karishma4Senate',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Karishma Manzur.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '8',
        name: 'Oliver Larkin',
        state: 'Florida',
        electionStatus: '',
        primaryElection: new Date('08/18/26'),
        generalElection: new Date('11/03/26'),
        handle: 'oliveralarkin',
        handleHref: 'https://x.com/OliverALarkin',
        bodyText:
            ' is proving Progressive politics is alive and well even in places like Florida! We are proud to endorse him and to do our part to help him win.',
        image: '/images/endorsement_images/2026/Silhouette/Oliver Larkin.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '9',
        name: 'Heath Howard',
        state: 'New Hampshire',
        electionStatus: '',
        primaryElection: new Date('09/08/26'),
        generalElection: new Date('11/03/26'),
        handle: 'heathhowardnh',
        handleHref: 'https://x.com/HeathHowardNH',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Heath Howard.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '10',
        name: 'Adam Murphy',
        state: 'Virginia',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'murphy4va',
        handleHref: 'https://x.com/Murphy4VA',
        bodyText:
            ' has quickly become a beloved presence in the PV community. We are proud to endorse him for Virginia’s 9th Congressional District.',
        image: '/images/endorsement_images/2026/Silhouette/Adam Murphy.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '11',
        name: 'Analilia Mejia',
        state: 'New Jersey',
        electionStatus: 'Elected',
        jurisdiction: 'CD11',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: 'analilia_mejia',
        handleHref: 'https://x.com/Analilia_Mejia',
        bodyText:
            ' is a life long organizer who will be instrumental in organizing the progressive movement from within congress! We are thrilled to endorse her, and to see her take the PV Pledge.',
        image: '/images/endorsement_images/2026/Silhouette/Analilia Mejia.png',
        websiteHref: 'https://www.analiliafornj.com',
        donateHref: 'https://secure.actblue.com/donate/analiliafornj',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '12',
        name: 'Mary Peltola',
        state: 'Alaska',
        electionStatus: '',
        primaryElection: new Date('08/18/26'),
        generalElection: new Date('11/03/26'),
        handle: 'marypeltola',
        handleHref: 'https://x.com/MaryPeltola',
        bodyText:
            " is America's first Native Alaskan representative and a fierce advocate for her community. We are proud to endorse her Alaska's Senate Seat!",
        image: '/images/endorsement_images/2026/Silhouette/Mary Peltola.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'Recommendation',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '13',
        name: 'Erica Watkins',
        state: 'Oklahoma',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/16/26'),
        generalElection: new Date('11/03/26'),
        handle: 'erica4ok',
        handleHref: 'https://x.com/erica4ok',
        bodyText:
            " stands apart not just as someone who will take on the machine, but someone with bold ideas to fight Oklahoma's poverty and exploitation.",
        image: '/images/endorsement_images/2026/Silhouette/Erica Watkins.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '14',
        name: 'Taylor Rehmet',
        state: 'Texas',
        electionStatus: 'Elected',
        generalElection: new Date('01/31/26'),
        handle: 'taylorrehmettx',
        handleHref: 'https://x.com/TaylorRehmetTX',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Taylor Rehmet.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '15',
        name: 'Luis Villarreal',
        state: 'Utah',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'luis4utah',
        handleHref: 'https://x.com/Luis4Utah',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Luis Villarreal.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '16',
        name: 'Brad Lander',
        state: 'New York',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'bradlander',
        handleHref: 'https://x.com/bradlander',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Brad Lander.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '17',
        name: 'Ro Khanna',
        state: 'California',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: 'rokhanna',
        handleHref: 'https://x.com/RoKhanna',
        bodyText:
            ' is the leader our party needs! His commitment to new media politics has made him an outstanding voice capable of real change.',
        image: '/images/endorsement_images/2026/Silhouette/Ro Khanna.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '18',
        name: 'Cori Bush',
        state: 'Missouri',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'coribush',
        handleHref: 'https://x.com/CoriBush',
        bodyText:
            ' is back to finish what she started! Her passion and tenacity have repeatedly shown that she is a powerful progressive voice ready to take on whatever battle is needed.',
        image: '/images/endorsement_images/2026/Silhouette/Cori Bush.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '19',
        name: 'James Talarico',
        state: 'Texas',
        electionStatus: 'Won Primary',
        primaryElection: new Date('03/03/26'),
        generalElection: new Date('11/03/26'),
        handle: 'jamestalarico',
        handleHref: 'https://x.com/jamestalarico',
        bodyText:
            "'s time has come to turn Texas blue. PV is proud to endorse him for the US Senate Seat in Texas! He is exctly what is needed.",
        image: '/images/endorsement_images/2026/Silhouette/James Talarico.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '21',
        name: 'Zeeshan Hafeez',
        state: 'Texas',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/03/26'),
        generalElection: new Date('11/03/26'),
        handle: 'zeeshanfortexas',
        handleHref: '',
        bodyText:
            " is going to bring a fire to Texa's 33rd Congressional District. We are excited to see a bold progressive like him making all the right waves in all the right places!",
        image: '/images/endorsement_images/2026/Silhouette/Zeeshan Hafeez.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '22',
        name: 'Michael Blake',
        state: 'New York',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'MrMikeBlake',
        handleHref: 'https://x.com/MrMikeBlake',
        bodyText:
            ' is an authentic, progressive fighter who has a deep love for his community. The progressive movement won in New Jersey and he will bring that momentum to New York!',
        image: '/images/endorsement_images/2026/Silhouette/Michael Blake.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '23',
        name: 'Aaron Bailey',
        state: 'Michigan',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'baileepolitics',
        handleHref: 'https://x.com/BaileePolitics',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Aaron Bailey.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '24',
        name: 'Adam Bojak',
        state: 'New York',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'bojak4assembly',
        handleHref: 'https://x.com/bojak4assembly',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Adam Bojak.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '25',
        name: 'Beth Andres-Beck',
        state: 'Massachusetts',
        electionStatus: '',
        primaryElection: new Date('09/01/26'),
        generalElection: new Date('11/03/26'),
        handle: 'beth4ma',
        handleHref: 'https://x.com/beth4ma',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Beth Andres-Beck.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '26',
        name: 'Blake Bracht',
        state: 'Arizona',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('07/21/26'),
        generalElection: new Date('11/03/26'),
        handle: 'brachtforaz5',
        handleHref: 'https://x.com/BrachtforAZ5',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Blake Bracht.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '27',
        name: 'Bobby Nichols',
        state: 'Arizona',
        electionStatus: 'Elected',
        generalElection: new Date('05/19/26'),
        handle: 'bobby4tempe',
        handleHref: 'https://www.instagram.com/bobby4tempe/',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Bobby Nichols.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '28',
        name: 'Brent Hennrich',
        state: 'Washington',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'bhennrich',
        handleHref: 'https://x.com/bhennrich',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Brent Hennrich.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '29',
        name: 'Ethan Wechtaluk',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'ethanformd',
        handleHref: 'https://x.com/ethanformd',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Ethan Wechtaluk.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '30',
        name: 'Greg Casar',
        state: 'Texas',
        electionStatus: 'Won Primary',
        primaryElection: new Date('03/03/26'),
        generalElection: new Date('11/03/26'),
        handle: 'gregcasar',
        handleHref: 'https://x.com/gregcasar',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Greg Casar.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '32',
        name: 'Hunter Gordon',
        state: 'Washington',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'hunter4wa',
        handleHref: 'https://x.com/hunter4wa',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Hunter Gordon.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '33',
        name: 'Jakeya Johnson',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'jakeya_hq',
        handleHref: 'https://www.instagram.com/jakeya_hq',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Jakeya Johnson.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '34',
        name: 'John Padora',
        state: 'Colorado',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('06/30/26'),
        generalElection: new Date('11/03/26'),
        handle: 'padoraforco',
        handleHref: 'https://x.com/PadoraforCO',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/John Padora.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '35',
        name: 'Josie Caballero',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'josieformd',
        handleHref: 'https://x.com/josieformd',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Josie Caballero.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'Endorsement',
        showPvMember: true,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '36',
        name: 'Katie Bansil',
        state: 'New Jersey',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: 'katiebansil4nj',
        handleHref: 'https://x.com/katiebansil4nj',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Katie Bansil.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '37',
        name: 'Matt Conroy',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/17/26'),
        generalElection: new Date('11/03/26'),
        handle: 'conroyforil',
        handleHref: 'https://x.com/ConroyForIL',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Matt Conroy.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '38',
        name: 'Matt Fulmer',
        state: 'South Carolina',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/09/26'),
        generalElection: new Date('11/03/26'),
        handle: 'mattforcarolina',
        handleHref: 'https://x.com/MattForCarolina',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Matt Fulmer.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '39',
        name: 'Maurice Brown',
        state: 'New York',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: 'electmauricebrown',
        handleHref: 'https://www.instagram.com/electmauricebrown',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Maurice Brown.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '40',
        name: 'Max Diaz',
        state: 'South Carolina',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/09/26'),
        generalElection: new Date('11/03/26'),
        handle: 'votemaxdiaz',
        handleHref: 'https://x.com/VoteMaxDiaz',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Max Diaz.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '41',
        name: 'Maxwell Alejandro Frost',
        state: 'Florida',
        electionStatus: 'Won Primary',
        primaryElection: new Date('08/18/26'),
        generalElection: new Date('11/03/26'),
        handle: 'maxwellfrostfl',
        handleHref: 'https://x.com/MaxwellFrostFL',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Alejandro Maxwell-Frost.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '42',
        name: 'Melissa Bird',
        state: 'Oregon',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: 'melissabirdforcongress',
        handleHref: 'https://www.instagram.com/melissabirdforcongress/',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Melissa Bird.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '44',
        name: 'Nida Allam',
        state: 'North Carolina',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        handleHref: 'https://x.com/NidaAllam',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Nida Allam.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '45',
        name: 'Robert Arnold',
        state: 'South Dakota',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: 'robertarnoldsd',
        handleHref: 'https://x.com/RobertArnoldSD',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Robert Arnold.png',
        websiteHref: '',
        initiativeType: 'state',

        endorsementType: 'Endorsement',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '46',
        name: 'Val Thomason',
        state: 'Nevada',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/09/26'),
        generalElection: new Date('11/03/26'),
        handle: 'valfornevada',
        handleHref: 'https://x.com/valfornevada',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Val Thomason.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '47',
        name: 'William Compton',
        state: 'Kentucky',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: 'compton4ky2024',
        handleHref: 'https://x.com/Compton4KY2024',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/William Compton.png',
        websiteHref: '',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '48',
        name: 'Hartzell Gray',
        state: 'Missouri',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: 'hartzellforkc',
        handleHref: 'https://x.com/hartzellforkc',
        bodyText:
            ' is a bold progressive proving that even in the deepest depths of Republican controlled Missouri, a platform of economic and social justice can make its mark.',
        image: '/images/endorsement_images/2026/Silhouette/Hartzell Gray.png',
        websiteHref: '',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '49',
        name: 'Jackson Franklin',
        state: 'Indiana',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('05/05/26'),
        generalElection: new Date('11/03/26'),
        handle: 'jacksonfrankli',
        handleHref: 'https://x.com/jacksonfrankli',
        bodyText:
            " has a passionate voice committed to fighting for a better world not just in the U.S. but around the world. We are proud to endorse him for Indiana's 5th Congressional District!",
        image: '/images/endorsement_images/2026/Silhouette/Jackson Franklin.png',
        websiteHref: 'https://jacksonfranklinforcongress.com/',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '50',
        name: 'Audrey Denny',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Audrey Denny.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '51',
        name: 'Abdun Matin',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Abdun Matin.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '52',
        name: 'Abel Chavez',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Abel Chavez.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '53',
        name: 'Adam Hamawy',
        state: 'New Jersey',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Adam Hamawy.png',
        websiteHref: '',
        initiativeType: 'national',
        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '54',
        name: 'Ali Aljarrah',
        state: 'New Jersey',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Ali Aljarrah.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '55',
        name: 'Chris Rabb',
        state: 'Pennsylvania',
        electionStatus: 'Won Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Chris Rabb.png',
        websiteHref: '',
        initiativeType: 'state',
        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '56',
        name: 'Charles Booker',
        state: 'Kentucky',
        electionStatus: 'Won Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Charles Booker.png',
        websiteHref: '',
        initiativeType: 'national',
        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '57',
        name: 'Chelsey Hockett',
        state: 'Texas',
        electionStatus: 'Won Primary',
        primaryElection: new Date('05/26/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Chelsey Hockett.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '58',
        name: 'Christopher Ahuja',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Christopher Ahuja.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '59',
        name: 'Chuck Park',
        state: 'New York',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Chuck Park.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '60',
        name: 'Dylan Blaha',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/17/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Dylan Blaha.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '61',
        name: 'Darializa Avila Chevalier',
        state: 'New York',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Darializa Avila Chevalier.png',
        websiteHref: '',
        initiativeType: 'national',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '62',
        name: 'Demi Palecek',
        state: 'Illinois',
        electionStatus: 'Won Primary',
        primaryElection: new Date('03/17/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Demi Palecek.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '63',
        name: 'Erin Petrey',
        state: 'Kentucky',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('05/19/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Erin Petrey.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '64',
        name: 'Evan Smith',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Evan Smith.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '65',
        name: 'Heidi Hall',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Heidi Hall.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '66',
        name: 'Imara Crooms',
        state: 'Maryland',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Imara Crooms.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '67',
        name: 'Jo Bennett',
        state: 'New York',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Jo Bennett.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '68',
        name: 'Jesse Brewer',
        state: 'Kentucky',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/19/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Jesse Brewer.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '69',
        name: 'Jillian Gilchrest',
        state: 'Connecticut',
        electionStatus: '',
        primaryElection: new Date('08/11/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Jillian Gilchrest.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '70',
        name: 'Julie Gonzales',
        state: 'Colorado',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/30/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Julie Gonzales.png',
        websiteHref: '',
        initiativeType: 'national',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '71',
        name: 'Junaid Ahmed',
        state: 'Illinois',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('03/17/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Junaid Ahmed.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '72',
        name: 'Kyle Gauck',
        state: 'Connecticut',
        electionStatus: '',
        primaryElection: new Date('08/11/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Kyle Gauck.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '73',
        name: 'Mai Vang',
        state: 'California',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Mai Vang.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '74',
        name: 'Matt Ortega',
        state: 'California',
        electionStatus: 'Dropped Out',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Matt Ortega.png',
        websiteHref: '',
        initiativeType: 'state',
        endorsementType: 'PV Pledge',
        showPvMember: true,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '75',
        name: 'Oliver Ma',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Oliver Ma.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '76',
        name: 'Omar Mohamad',
        state: 'New York',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Omar Mohamad.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '77',
        name: 'Paige Loud',
        state: 'Maine',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/09/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Paige Loud.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '78',
        name: 'Raj Goyle',
        state: 'New York',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Raj Goyle.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '79',
        name: 'Rose Penelope Yee',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Rose Penelope Yee.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '80',
        name: 'Tom Steyer',
        state: 'California',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Tom Steyer.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '81',
        name: 'Tammy Honeywell',
        state: 'New York',
        electionStatus: 'Lost Primary',
        primaryElection: new Date('06/23/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Tammy Honeywell.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '82',
        name: 'Tessa Lynn Hodge',
        state: 'California',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/02/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Tessa Lynn Hodge.png',
        websiteHref: '',
        initiativeType: '',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    {
        id: '83',
        name: 'William Lawrence',
        state: 'Michigan',
        electionStatus: 'Won Primary',
        primaryElection: new Date('08/04/26'),
        generalElection: new Date('11/03/26'),
        handle: '',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/William Lawrence.png',
        websiteHref: '',
        initiativeType: 'national',
        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'yellow',
    },

    {
        id: '93',
        name: 'Melat Kiros',
        state: 'Colorado',
        electionStatus: 'Won Primary',
        primaryElection: new Date('06/30/26'),
        generalElection: new Date('11/03/26'),
        handle: 'MelatKirosCO',
        handleHref: 'https://x.com/MelatKirosCO',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Melat Kiros.png',
        websiteHref: 'https://www.kirosforco.com',
        initiativeType: 'national',

        endorsementType: 'PV Pledge',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },
    {
        id: '94',
        name: 'Francesca Hong',
        state: 'Wisconsin',
        electionStatus: '',
        primaryElection: new Date('08/11/26'),
        generalElection: new Date('11/03/26'),
        handle: 'FrancescaHongWI',
        handleHref: 'https://x.com/FrancescaHongWI',
        bodyText: '',
        image: '/images/endorsement_images/2026/Silhouette/Francesca Hong.png',
        websiteHref: 'https://francescahong.com',
        initiativeType: '',

        endorsementType: 'Endorsement',
        showPvMember: false,
        avatarBackgroundColor: 'blue',
    },

    // {
    //     id: '84',
    //     name: 'Katie Wilson',
    //     state: 'Washington',
    //     electionStatus: 'Elected',
    //     primaryElection: new Date('08/05/25'),
    //     generalElection: new Date('11/04/25'),
    //     handle: 'MayorofSeattle',
    //     handleHref: 'https://x.com/MayorofSeattle',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'blue',
    // },

    // {
    //     id: '85',
    //     name: 'Zohran Mamdani',
    //     state: 'New York',
    //     electionStatus: 'Elected',
    //     primaryElection: new Date('06/24/25'),
    //     generalElection: new Date('11/04/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '86',
    //     name: 'Ras Baraka',
    //     state: 'New Jersey',
    //     electionStatus: 'Lost Primary',
    //     primaryElection: new Date('06/10/25'),
    //     generalElection: new Date('11/04/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '87',
    //     name: 'Mikie Sherrill',
    //     state: 'New Jersey',
    //     electionStatus: 'Elected',
    //     primaryElection: new Date('06/10/25'),
    //     generalElection: new Date('11/04/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Recommendation',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '88',
    //     name: 'Deja Foxx',
    //     state: 'Arizona',
    //     electionStatus: 'Lost General',
    //     generalElection: new Date('06/15/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'blue',
    // },

    // {
    //     id: '89',
    //     name: 'Jonas Eppert',
    //     state: 'Virginia',
    //     electionStatus: 'Lost General',
    //     generalElection: new Date('11/04/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'state',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '90',
    //     name: 'Ben Wikler',
    //     state: 'Nationwide',
    //     electionStatus: 'Lost General',
    //     generalElection: new Date('02/01/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '91',
    //     name: 'Susan Crawford',
    //     state: 'Wisconsin',
    //     electionStatus: 'Elected',
    //     generalElection: new Date('04/01/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'blue',
    // },

    // {
    //     id: '92',
    //     name: 'Joshua Weil',
    //     state: 'Florida',
    //     electionStatus: 'Lost General',
    //     generalElection: new Date('04/01/25'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },

    // {
    //     id: '94',
    //     name: 'Kamala Harris',
    //     state: 'President',
    //     electionStatus: 'Lost General',
    //     generalElection: new Date('11/05/24'),
    //     handle: '',
    //     handleHref: '',
    //     bodyText: '',
    //     image: '',
    //     websiteHref: '',
    //     initiativeType: 'national',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'blue',
    // },

    // {
    //     id: '95',
    //     name: 'Mary Peltola',
    //     state: 'Alaska',
    //     electionStatus: 'Lost General',
    //     primaryElection: new Date('08/20/24'),
    //     generalElection: new Date('11/05/24'),
    //     handle: 'marypeltola',
    //     handleHref: 'https://x.com/MaryPeltola',
    //     bodyText:
    //         " is America's first Native Alaskan representative and a fierce advocate for her community. We are proud to endorse her for re-election in Alaska's at-large congressional district!",
    //     image: '/images/endorsement_images/2026/Silhouette/Mary Peltola.png',
    //     websiteHref: '',
    //     initiativeType: 'state',

    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'blue',
    // },

    //angela alsobrook
    //jamaal bowman
    //summer lee
    //canvass house people
    //canvass event people

    // {
    //     id: '20',
    //     name: 'Jon Stewart',
    //     state: 'President',
    //     electionStatus: '',
    //     primaryElection: new Date('11/07/28'),
    //     generalElection: new Date('11/07/28'),
    //     handle: 'jonstewart',
    //     handleHref: 'https://x.com/jonstewart',
    //     bodyText:
    //         ' isn’t perfect, but his decades long track record of integrity and progressivism make him the decisive pick. We urge him to serve his country by running for the office.',
    //     image: '/images/endorsement_images/2026/Silhouette/Jon Stewart.png',
    //     websiteHref: '',
    //     initiativeType: '',
    //     endorsementType: 'Endorsement',
    //     showPvMember: false,
    //     avatarBackgroundColor: 'yellow',
    // },
]
