name: Deploy to Dev
on:
  push:
    branches: [dev]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: Dockerfile
      REPLACE_ENV_FILE: deployment/deployment.env
      ENV_FILE: .env
      TAG: api_dev
    steps:
     - uses: actions/checkout@v2
     - name: Replace Appsettings
       run: cp ${{env.REPLACE_ENV_FILE}} ${{env.ENV_FILE}}
     - name: Log in to the Container registry
       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build and push Docker images
       id: push
       uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
       with:
         context: .
         push: true
         tags: ${{ env.TAG }}
