name: Test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Preview
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run tests
              run: pnpm test
